image: java:8-jdk

stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

temporal_build:
  stage: build
  script:
    - ./gradlew shadowJar
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    paths:
      - build/libs/wotgate-*-fat.jar
      - README.md
    expire_in: 2 weeks
  only:
    - mockedwotgate
    - mockedwotgate2

build:
  stage: build
  script:
    - ./gradlew shadowJar
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    paths:
      - build/libs/wotgate-*-fat.jar
      - README.md
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

after_script:
- echo "End CI"